### ISSUE TITLE
[feat] 添加markdownlint和保存时自动格式化插件

### ISSUE THREAD

**Issue by AlphaFoxz** [ddd-fans/ddd-guideline#2]
保证多人协作时的文档格式统一

**Comment by AlphaFoxz** [comment]
## 对于JB系列的ide
添加.editorconfig文件，内容如下
```toml
root = true

[*.md]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

## 对于vscode
添加 `.vscode/extensions.json` 文件和 `.vscode/settings.json` 文件，
用 prettier 和 markdownlint 来约束、自动格式化
